In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pandas as pd

In [38]:
df = pd.read_csv('california_cities.csv')
df.head()

,Unnamed: 0,city,latd,longd,elevation_m,elevation_ft,population_total,area_total_sq_mi,area_land_sq_mi,area_water_sq_mi,area_total_km2,area_land_km2,area_water_km2,area_water_percent
0,0,Adelanto,34.576111,-117.432778,875.0,2871.0,31765,56.027,56.009,0.018,145.107,145.062,0.046,0.03
1,1,AgouraHills,34.153333,-118.761667,281.0,922.0,20330,7.822,7.793,0.029,20.260,20.184,0.076,0.37
2,2,Alameda,37.756111,-122.274444,NaN,33.0,75467,22.960,10.611,12.349,59.465,27.482,31.983,53.79
3,3,Albany,37.886944,-122.297778,NaN,43.0,18969,5.465,1.788,3.677,14.155,4.632,9.524,67.28
4,4,Alhambra,34.081944,-118.135000,150.0,492.0,83089,7.632,7.631,0.001,19.766,19.763,0.003,0.01

In [30]:
df.columns

Index(['Unnamed: 0', 'city', 'latd', 'longd', 'elevation_m', 'elevation_ft',
       'population_total', 'area_total_sq_mi', 'area_land_sq_mi',
       'area_water_sq_mi', 'area_total_km2', 'area_land_km2', 'area_water_km2',
       'area_water_percent'],
      dtype='object')

Part - I Idetification and Clearning Missing Values

In [31]:
#Find out the missing values in each column and store them in the variable col_missing_values
col_missing_values = df.isna().sum()
col_missing_values

Unnamed: 0             0
city                   0
latd                   0
longd                  0
elevation_m           48
elevation_ft          12
population_total       0
area_total_sq_mi       2
area_land_sq_mi        0
area_water_sq_mi       1
area_total_km2         5
area_land_km2          4
area_water_km2         4
area_water_percent     5
dtype: int64

In [12]:
#Which Column has the most number of missing values?
col_missing_values.sort_values(ascending=False).head(1)

elevation_m    48
dtype: int64

In [25]:
#Which Column has the minimum missing values?
col_missing_values.sort_values().head(6)

Unnamed: 0          0
city                0
latd                0
longd               0
population_total    0
area_land_sq_mi     0
dtype: int64

In [26]:
#How many values of the column elevation_m are missing?
col_missing_values['elevation_m']

48

In [32]:
#Find the total missing values in the whole dataset and store the number in df_missing_values
col_missing_values.sum()

81

In [39]:
#Drop the column area_water_percent
df.drop(columns=['area_water_percent'],inplace=True)
df

,Unnamed: 0,city,latd,longd,elevation_m,elevation_ft,population_total,area_total_sq_mi,area_land_sq_mi,area_water_sq_mi,area_total_km2,area_land_km2,area_water_km2
0,0,Adelanto,34.576111,-117.432778,875.0,2871.0,31765,56.027,56.009,0.018,145.107,145.062,0.046
1,1,AgouraHills,34.153333,-118.761667,281.0,922.0,20330,7.822,7.793,0.029,20.260,20.184,0.076
2,2,Alameda,37.756111,-122.274444,NaN,33.0,75467,22.960,10.611,12.349,59.465,27.482,31.983
3,3,Albany,37.886944,-122.297778,NaN,43.0,18969,5.465,1.788,3.677,14.155,4.632,9.524
4,4,Alhambra,34.081944,-118.135000,150.0,492.0,83089,7.632,7.631,0.001,19.766,19.763,0.003
...,...,...,...,...,...,...,...,...,...,...,...,...,...
477,477,Yountville,38.403056,-122.362222,30.0,98.0,2933,1.531,1.531,0.000,3.966,3.966,0.000
478,478,Yreka,41.726667,-122.637500,787.0,2582.0,7765,10.053,9.980,0.073,26.036,25.847,0.188
479,479,YubaCity,39.134722,-121.626111,18.0,59.0,64925,14.656,14.578,0.078,37.959,37.758,0.201
480,480,Yucaipa,34.030278,-117.048611,798.0,2618.0,51367,27.893,27.888,0.005,72.244,72.231,0.013
481,481,YuccaValley,34.133333,-116.416667,1027.0,3369.0,20700,40.015,40.015,0.000,103.639,103.639,0.000

In [40]:
#Drop the rows having missing values and store your resulting DataFrame in the variable
df_narows_dropped = df.dropna()
df_narows_dropped

,Unnamed: 0,city,latd,longd,elevation_m,elevation_ft,population_total,area_total_sq_mi,area_land_sq_mi,area_water_sq_mi,area_total_km2,area_land_km2,area_water_km2
0,0,Adelanto,34.576111,-117.432778,875.0,2871.0,31765,56.027,56.009,0.018,145.107,145.062,0.046
1,1,AgouraHills,34.153333,-118.761667,281.0,922.0,20330,7.822,7.793,0.029,20.260,20.184,0.076
4,4,Alhambra,34.081944,-118.135000,150.0,492.0,83089,7.632,7.631,0.001,19.766,19.763,0.003
5,5,AlisoViejo,33.575000,-117.725556,127.0,417.0,47823,7.472,7.472,0.000,19.352,19.352,0.000
6,6,Alturas,41.487222,-120.542500,1332.0,4370.0,2827,2.449,2.435,0.014,6.342,6.306,0.036
...,...,...,...,...,...,...,...,...,...,...,...,...,...
477,477,Yountville,38.403056,-122.362222,30.0,98.0,2933,1.531,1.531,0.000,3.966,3.966,0.000
478,478,Yreka,41.726667,-122.637500,787.0,2582.0,7765,10.053,9.980,0.073,26.036,25.847,0.188
479,479,YubaCity,39.134722,-121.626111,18.0,59.0,64925,14.656,14.578,0.078,37.959,37.758,0.201
480,480,Yucaipa,34.030278,-117.048611,798.0,2618.0,51367,27.893,27.888,0.005,72.244,72.231,0.013
481,481,YuccaValley,34.133333,-116.416667,1027.0,3369.0,20700,40.015,40.015,0.000,103.639,103.639,0.000

In [41]:
#Drop Rows with More Than 5 Missing Values
df_rows_dropped = df.dropna(thresh=5,axis=0)
df_rows_dropped

,Unnamed: 0,city,latd,longd,elevation_m,elevation_ft,population_total,area_total_sq_mi,area_land_sq_mi,area_water_sq_mi,area_total_km2,area_land_km2,area_water_km2
0,0,Adelanto,34.576111,-117.432778,875.0,2871.0,31765,56.027,56.009,0.018,145.107,145.062,0.046
1,1,AgouraHills,34.153333,-118.761667,281.0,922.0,20330,7.822,7.793,0.029,20.260,20.184,0.076
2,2,Alameda,37.756111,-122.274444,NaN,33.0,75467,22.960,10.611,12.349,59.465,27.482,31.983
3,3,Albany,37.886944,-122.297778,NaN,43.0,18969,5.465,1.788,3.677,14.155,4.632,9.524
4,4,Alhambra,34.081944,-118.135000,150.0,492.0,83089,7.632,7.631,0.001,19.766,19.763,0.003
...,...,...,...,...,...,...,...,...,...,...,...,...,...
477,477,Yountville,38.403056,-122.362222,30.0,98.0,2933,1.531,1.531,0.000,3.966,3.966,0.000
478,478,Yreka,41.726667,-122.637500,787.0,2582.0,7765,10.053,9.980,0.073,26.036,25.847,0.188
479,479,YubaCity,39.134722,-121.626111,18.0,59.0,64925,14.656,14.578,0.078,37.959,37.758,0.201
480,480,Yucaipa,34.030278,-117.048611,798.0,2618.0,51367,27.893,27.888,0.005,72.244,72.231,0.013
481,481,YuccaValley,34.133333,-116.416667,1027.0,3369.0,20700,40.015,40.015,0.000,103.639,103.639,0.000

In [42]:
#Remove Columns with Missing Values
df_nacols_dropped = df.dropna(axis=1)
df_nacols_dropped

,Unnamed: 0,city,latd,longd,population_total,area_land_sq_mi
0,0,Adelanto,34.576111,-117.432778,31765,56.009
1,1,AgouraHills,34.153333,-118.761667,20330,7.793
2,2,Alameda,37.756111,-122.274444,75467,10.611
3,3,Albany,37.886944,-122.297778,18969,1.788
4,4,Alhambra,34.081944,-118.135000,83089,7.631
...,...,...,...,...,...,...
477,477,Yountville,38.403056,-122.362222,2933,1.531
478,478,Yreka,41.726667,-122.637500,7765,9.980
479,479,YubaCity,39.134722,-121.626111,64925,14.578
480,480,Yucaipa,34.030278,-117.048611,51367,27.888
481,481,YuccaValley,34.133333,-116.416667,20700,40.015

In [46]:
#Drop colomns with more than 10 missing values and store the resulting DataFrame in the variable df_cols_dropped
df_cols_dropped = df.dropna(axis=1, thresh=len(df) - 10)
df_cols_dropped

,Unnamed: 0,city,latd,longd,population_total,area_total_sq_mi,area_land_sq_mi,area_water_sq_mi,area_total_km2,area_land_km2,area_water_km2
0,0,Adelanto,34.576111,-117.432778,31765,56.027,56.009,0.018,145.107,145.062,0.046
1,1,AgouraHills,34.153333,-118.761667,20330,7.822,7.793,0.029,20.260,20.184,0.076
2,2,Alameda,37.756111,-122.274444,75467,22.960,10.611,12.349,59.465,27.482,31.983
3,3,Albany,37.886944,-122.297778,18969,5.465,1.788,3.677,14.155,4.632,9.524
4,4,Alhambra,34.081944,-118.135000,83089,7.632,7.631,0.001,19.766,19.763,0.003
...,...,...,...,...,...,...,...,...,...,...,...
477,477,Yountville,38.403056,-122.362222,2933,1.531,1.531,0.000,3.966,3.966,0.000
478,478,Yreka,41.726667,-122.637500,7765,10.053,9.980,0.073,26.036,25.847,0.188
479,479,YubaCity,39.134722,-121.626111,64925,14.656,14.578,0.078,37.959,37.758,0.201
480,480,Yucaipa,34.030278,-117.048611,51367,27.893,27.888,0.005,72.244,72.231,0.013
481,481,YuccaValley,34.133333,-116.416667,20700,40.015,40.015,0.000,103.639,103.639,0.000

Part - II Data Imputation Methods

In [45]:
#Fill the missing values in elevation_m with -999. Store your result in the variable filled_elevation_m
filled_elevation_m = df['elevation_m'].fillna(-999)
filled_elevation_m

0       875.0
1       281.0
2      -999.0
3      -999.0
4       150.0
        ...
477      30.0
478     787.0
479      18.0
480     798.0
481    1027.0
Name: elevation_m, Length: 482, dtype: float64

In [47]:
#Fill the missing values in area_total_km2 with the value 0 permanently, store your result in the variable filled_area_total
filled_area_total = df['area_total_km2'].fillna(0,inplace=True)

In [48]:
#Fill the missing values of the column latd using backward filling method and store your result in the variable bfill_latd
bfill_latd = df['latd'].bfill()
bfill_latd

0      34.576111
1      34.153333
2      37.756111
3      37.886944
4      34.081944
         ...
477    38.403056
478    41.726667
479    39.134722
480    34.030278
481    34.133333
Name: latd, Length: 482, dtype: float64

In [49]:
#Fill the missing values of the column longd using forwarding filling method and store your result in the variable ffill_longd
#limit=15 parameter is used to limit the number of consecutive missing values to be filled
ffill_longd = df['longd'].ffill()
ffill_longd

0     -117.432778
1     -118.761667
2     -122.274444
3     -122.297778
4     -118.135000
          ...
477   -122.362222
478   -122.637500
479   -121.626111
480   -117.048611
481   -116.416667
Name: longd, Length: 482, dtype: float64

In [50]:
#Fill the missing values of the column population_total with the mean of the column and store your result in the variable mean_total_population
mean_total_population = df['population_total'].fillna(df['population_total'].mean())
mean_total_population

0      31765
1      20330
2      75467
3      18969
4      83089
       ...
477     2933
478     7765
479    64925
480    51367
481    20700
Name: population_total, Length: 482, dtype: int64

In [51]:
#Fill the missing values of the column area_water_sq_mi with the median value of the column and store your result in the variable median_fill
median_fill = df['area_water_sq_mi'].fillna(df['area_water_sq_mi'].median())
median_fill

0       0.018
1       0.029
2      12.349
3       3.677
4       0.001
        ...
477     0.000
478     0.073
479     0.078
480     0.005
481     0.000
Name: area_water_sq_mi, Length: 482, dtype: float64

In [53]:
df['area_land_km2'].mode()

0     3.496
1    20.541
Name: area_land_km2, dtype: float64

In [54]:
#Fill the missing values of the column area_land_km2 with the mode value of the column and store your result in the variable mode_fill
#mode can have 2 values so we use the first
mode_fill = df['area_land_km2'].fillna(df['area_land_km2'].mode()[0])
mode_fill

0      145.062
1       20.184
2       27.482
3        4.632
4       19.763
        ...
477      3.966
478     25.847
479     37.758
480     72.231
481    103.639
Name: area_land_km2, Length: 482, dtype: float64

In [56]:
#Write following code will fill the missing values in the DataFrame with zeros and store your result in a variable filled_df
filled_df = df.fillna(0)
filled_df

,Unnamed: 0,city,latd,longd,elevation_m,elevation_ft,population_total,area_total_sq_mi,area_land_sq_mi,area_water_sq_mi,area_total_km2,area_land_km2,area_water_km2
0,0,Adelanto,34.576111,-117.432778,875.0,2871.0,31765,56.027,56.009,0.018,145.107,145.062,0.046
1,1,AgouraHills,34.153333,-118.761667,281.0,922.0,20330,7.822,7.793,0.029,20.260,20.184,0.076
2,2,Alameda,37.756111,-122.274444,0.0,33.0,75467,22.960,10.611,12.349,59.465,27.482,31.983
3,3,Albany,37.886944,-122.297778,0.0,43.0,18969,5.465,1.788,3.677,14.155,4.632,9.524
4,4,Alhambra,34.081944,-118.135000,150.0,492.0,83089,7.632,7.631,0.001,19.766,19.763,0.003
...,...,...,...,...,...,...,...,...,...,...,...,...,...
477,477,Yountville,38.403056,-122.362222,30.0,98.0,2933,1.531,1.531,0.000,3.966,3.966,0.000
478,478,Yreka,41.726667,-122.637500,787.0,2582.0,7765,10.053,9.980,0.073,26.036,25.847,0.188
479,479,YubaCity,39.134722,-121.626111,18.0,59.0,64925,14.656,14.578,0.078,37.959,37.758,0.201
480,480,Yucaipa,34.030278,-117.048611,798.0,2618.0,51367,27.893,27.888,0.005,72.244,72.231,0.013
481,481,YuccaValley,34.133333,-116.416667,1027.0,3369.0,20700,40.015,40.015,0.000,103.639,103.639,0.000

In [ ]:
#Which of the following is/are the general structure for filling a column values with any value (mean, mode, or median)
df['column_name'].fillna(df['column_name'].mean())
df['column_name'].fillna(df['column_name'].mode()[0])
df['column_name'].fillna(df['column_name'].median())